version: '3.0'
services:
        # berserkr-app
        berserkr-app:
                container_name: berserkr-app
                image: berserkr-app
                build:
                        context: ../../
                        dockerfile: tools/docker/Dockerfile
                depends_on:
                  - minio
                network_mode: 'host'
        # MinIO simulate S3 for local smoke and unit/integration testing
        minio:
                image: minio/minio
                ports:
                        - '9000:9000'
                volumes:
                        - ./test/.minio/data:/export
                        - ./test/.minio/config:/root/.minio
                environment:
                        - 'MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE'
                        - 'MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY'
                command: server /export
        # Initial raw data
        createrawdatabucket:
                image: minio/mc
                depends_on:
                        - minio
                entrypoint: >
                        /bin/sh -c "
                        /usr/bin/mc config host add myminio http://minio:9000 AKIAIOSFODNN7EXAMPLE wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY;
                        /usr/bin/mc mb myminio/onlineretailraw;
                        /usr/bin/mc mb myminio/onlineretailparquet;
                        exit 0;"
                network_mode: 'host'
networks:
  berserkr-app-default:
